[target.x86_64-unknown-none]
rustflags = ["-C", "relocation-model=static"]

[unstable]
bindeps = true

[sources.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
